# Generated by Django 2.0 on 2018-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafeName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
